---

ntp_servers:
    - "0.pool.ntp.org"
    - "1.pool.ntp.org"
    - "2.pool.ntp.org"
    - "3.pool.ntp.org"

timezone: "UTC"

valid_hostname:
  unit1: "lab1.local.net"
  unit2: "lab2.local.net"

csync: "10.50.50.1"